import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

import {cn} from "@/lib/utils"

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Math E-Learning Platform",
  description: "GENERATED BY : ZABAQIST IT'S MOVE.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <head/>
      <body
          className={cn(
              "min-h-screen bg-background font-sans antialiased",
              inter.variable
          )}
      >{children}</body>
      </html>
  );
}
