import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import ClientLayout from './ClientLayout';


const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Math E-Learning Platform",
  description: "GENERATED BY : ZABAQIST IT'S MOVE.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <head/>
      <ClientLayout interVariable={inter.variable}>
          {children}
      </ClientLayout>
      </html>
  );
}
